[package]
name = "zfs_webmanager_agent"
version = "0.3.3"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"
libzetta = "0.5.0"
libzfs = "0.6.16"
dirs = "5.0"
